### ISSUE TITLE
[Ticket]: sqlite_offline_first example fails to compile in isolation (embedded-only feature masking)

### ISSUE THREAD

**Issue by stephane-segning** [cratestack/cratestack#108]
**Type:** Bug

### Summary

We need to fix the `sqlite_offline_first` embedded example so it compiles via its own documented command, because today it only builds under a full `--workspace` build and fails when a consumer builds the embedded surface on its own.

Expected result: `cargo run --example sqlite_offline_first -p cratestack-sqlite` compiles and runs.

### Intent

The embedded examples must build in the exact configuration an embedded consumer uses (rusqlite facade, no Postgres crate in the graph). An example that only compiles because an unrelated workspace member unifies a Cargo feature is misleading and breaks the documented "run this example" flow.

### Source of truth (links)

- Found during a full example-suite verification pass on branch `claude/trusting-tesla-c08e9d` (ran `cargo run` / `cargo build` over every example).
- The example's own doc-comment and `examples/README.md` document `cargo run --example sqlite_offline_first -p cratestack-sqlite` as the way to run it.
- Fix PR: #106.

### Current Behavior

```
cargo run --example sqlite_offline_first -p cratestack-sqlite
error[E0277]: the trait bound `rust_decimal::error::Error: StdError` is not satisfied
  --> crates/cratestack-sqlite/examples/sqlite_offline_first.rs:79 and :95
```

`cargo build --workspace` is green because `sqlx-postgres` pulls `rust_decimal` **with** its `std` feature, and Cargo feature-unification then makes `rust_decimal::error::Error: std::error::Error` hold for the embedded example too. Built in isolation, the embedded facade pulls `rust_decimal` with `serde-str` but not `std`, so the `?` conversion fails.

### Expected Behavior

The example compiles and runs both standalone (`-p cratestack-sqlite`) and under `--workspace`, and CI catches embedded-only breakage of this kind.

### Acceptance Criteria

- [ ] Given the embedded facade built in isolation, when `cargo build -p cratestack-sqlite --examples` runs, then it succeeds.
- [ ] Given the example, when run via `cargo run --example sqlite_offline_first -p cratestack-sqlite`, then it prints the seeded accounts/transfers and exits 0.
- [ ] A CI gate builds the embedded examples in isolation so this masking can't recur.
- [ ] Existing behavior is not broken (`--workspace` build/tests still pass).

### Test Plan

- `cargo run --example sqlite_offline_first -p cratestack-sqlite`
- `cargo build --locked -p cratestack-sqlite --examples`
- `cargo build --locked -p embedded-cli-example -p embedded-daemon-example -p embedded-webhook-example`
- Full CI (check + clippy + rustfmt + tests/Postgres).

### Verification evidence

After the fix, the standalone command runs to completion (seeded accounts + transfers printed, exit 0), the new `embedded examples (isolated build)` CI job passes, and `check` / `clippy` / `rustfmt` / `tests (ephemeral Postgres)` all pass on #106.

### Human accountable owner

@stephane-segning

### AI Usage Declaration

Understanding code; refactoring; reviewing the diff; drafting this ticket. AI output reviewed by the accountable owner.
